/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as OauthConsentRouteImport } from './routes/oauth.consent'
import { Route as ApiTransactionsRouteImport } from './routes/api/transactions'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as AuthedTransactionsRouteImport } from './routes/_authed/transactions'
import { Route as AuthedReportRouteImport } from './routes/_authed/report'
import { Route as AuthedFaturasRouteImport } from './routes/_authed/faturas'
import { Route as AuthedAccountsRouteImport } from './routes/_authed/accounts'
import { Route as DotwellKnownOauthProtectedResourceRouteImport } from './routes/[.]well-known.oauth-protected-resource'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known.oauth-authorization-server'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AuthedFaturasAccountIdRouteImport } from './routes/_authed/faturas_.$accountId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTransactionsRoute = ApiTransactionsRouteImport.update({
  id: '/api/transactions',
  path: '/api/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTransactionsRoute = AuthedTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReportRoute = AuthedReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFaturasRoute = AuthedFaturasRouteImport.update({
  id: '/faturas',
  path: '/faturas',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountsRoute = AuthedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthedRoute,
} as any)
const DotwellKnownOauthProtectedResourceRoute =
  DotwellKnownOauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedFaturasAccountIdRoute = AuthedFaturasAccountIdRouteImport.update({
  id: '/faturas_/$accountId',
  path: '/faturas/$accountId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/accounts': typeof AuthedAccountsRoute
  '/faturas': typeof AuthedFaturasRoute
  '/report': typeof AuthedReportRoute
  '/transactions': typeof AuthedTransactionsRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/transactions': typeof ApiTransactionsRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/faturas/$accountId': typeof AuthedFaturasAccountIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/accounts': typeof AuthedAccountsRoute
  '/faturas': typeof AuthedFaturasRoute
  '/report': typeof AuthedReportRoute
  '/transactions': typeof AuthedTransactionsRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/transactions': typeof ApiTransactionsRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/': typeof AuthedIndexRoute
  '/faturas/$accountId': typeof AuthedFaturasAccountIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/_authed/accounts': typeof AuthedAccountsRoute
  '/_authed/faturas': typeof AuthedFaturasRoute
  '/_authed/report': typeof AuthedReportRoute
  '/_authed/transactions': typeof AuthedTransactionsRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/transactions': typeof ApiTransactionsRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/faturas_/$accountId': typeof AuthedFaturasAccountIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/accounts'
    | '/faturas'
    | '/report'
    | '/transactions'
    | '/api/mcp'
    | '/api/transactions'
    | '/oauth/consent'
    | '/faturas/$accountId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/accounts'
    | '/faturas'
    | '/report'
    | '/transactions'
    | '/api/mcp'
    | '/api/transactions'
    | '/oauth/consent'
    | '/'
    | '/faturas/$accountId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/_authed/accounts'
    | '/_authed/faturas'
    | '/_authed/report'
    | '/_authed/transactions'
    | '/api/mcp'
    | '/api/transactions'
    | '/oauth/consent'
    | '/_authed/'
    | '/_authed/faturas_/$accountId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRoute
  DotwellKnownOauthProtectedResourceRoute: typeof DotwellKnownOauthProtectedResourceRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiTransactionsRoute: typeof ApiTransactionsRoute
  OauthConsentRoute: typeof OauthConsentRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transactions': {
      id: '/api/transactions'
      path: '/api/transactions'
      fullPath: '/api/transactions'
      preLoaderRoute: typeof ApiTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/transactions': {
      id: '/_authed/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthedTransactionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/report': {
      id: '/_authed/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AuthedReportRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/faturas': {
      id: '/_authed/faturas'
      path: '/faturas'
      fullPath: '/faturas'
      preLoaderRoute: typeof AuthedFaturasRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/accounts': {
      id: '/_authed/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthedAccountsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/faturas_/$accountId': {
      id: '/_authed/faturas_/$accountId'
      path: '/faturas/$accountId'
      fullPath: '/faturas/$accountId'
      preLoaderRoute: typeof AuthedFaturasAccountIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAccountsRoute: typeof AuthedAccountsRoute
  AuthedFaturasRoute: typeof AuthedFaturasRoute
  AuthedReportRoute: typeof AuthedReportRoute
  AuthedTransactionsRoute: typeof AuthedTransactionsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedFaturasAccountIdRoute: typeof AuthedFaturasAccountIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAccountsRoute: AuthedAccountsRoute,
  AuthedFaturasRoute: AuthedFaturasRoute,
  AuthedReportRoute: AuthedReportRoute,
  AuthedTransactionsRoute: AuthedTransactionsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedFaturasAccountIdRoute: AuthedFaturasAccountIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRoute,
  DotwellKnownOauthProtectedResourceRoute:
    DotwellKnownOauthProtectedResourceRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiTransactionsRoute: ApiTransactionsRoute,
  OauthConsentRoute: OauthConsentRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
